version: '3'
services:
  task_management:
    build: .
    command: python task_management/app.py
    ports:
      - "5000:5000"
  crm_chatbot:
    build: .
    command: uvicorn crm_chatbot.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
